### ISSUE TITLE
Option to temporarily disable project reload

### ISSUE THREAD

**Issue by wodzuu** [ethlo/lamebda#52]
Sometimes it is useful to temporarily stop automatic reload of selected lamebda project. For example when one wants to edit configuration files and replace lamebda jar file that can act on the new setup.

One option to solve this is to check if project folder contains a file of some pre-defined name (for example `.noreload`). As long as the file is present the project does not get reloaded (but is still watched for changes so that as soon as the file is removed the project gets reloaded).

**Comment by ethlo** [comment]
The reload handler will now check for the presence of a `.no_reload` file in the project path. Released in 1.4.0.
